# Generated by Django 3.1.1 on 2020-09-16 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='photo_url',
            field=models.URLField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='photographerprofile',
            name='image_url',
            field=models.URLField(max_length=500),
        ),
    ]
