# Generated by Django 3.1.1 on 2020-09-17 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200916_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='photographerprofile',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
