# Generated by Django 3.1.1 on 2020-09-17 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200917_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='prospect_list',
            field=models.ManyToManyField(blank=True, to='api.PhotographerProfile'),
        ),
    ]
