# Generated by Django 3.1.1 on 2020-10-14 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('api', '0004_auto_20200917_1844'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatorProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=100)),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.user')),
                ('tags', models.ManyToManyField(blank=True, to='api.Tag')),
            ],
            options={
                'verbose_name_plural': 'creator_profiles',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('image_url', models.URLField(max_length=500)),
                ('creator_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.creatorprofile')),
            ],
            options={
                'verbose_name_plural': 'images',
            },
        ),
        migrations.RemoveField(
            model_name='photographerprofile',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='photographerprofile',
            name='tags',
        ),
        migrations.AlterModelOptions(
            name='customerprofile',
            options={'verbose_name_plural': 'customer_profiles'},
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
        migrations.DeleteModel(
            name='PhotographerProfile',
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='prospect_list',
            field=models.ManyToManyField(blank=True, related_name='supporters', to='api.CreatorProfile'),
        ),
    ]
